[0m18:36:00.813723 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10800e3c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1089d3590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1089d32c0>]}


============================== 18:36:00.816754 | d3647718-299d-4168-87da-de27ff61321c ==============================
[0m18:36:00.816754 [info ] [MainThread]: Running with dbt=1.8.9
[0m18:36:00.817071 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/friedrichtenhagen/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt init marketing_dwh', 'send_anonymous_usage_stats': 'True'}
[0m18:36:00.827017 [debug] [MainThread]: Starter project path: /Users/friedrichtenhagen/coding/marketing_data_engineering_project/marketing_dwh_env/lib/python3.12/site-packages/dbt/include/starter_project
[0m18:36:00.830575 [info ] [MainThread]: 
Your new dbt project "marketing_dwh" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:36:00.830868 [info ] [MainThread]: Setting up your profile.
[0m18:36:27.671683 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 26.897284, "process_in_blocks": "0", "process_kernel_time": 0.118804, "process_mem_max_rss": "105103360", "process_out_blocks": "0", "process_user_time": 0.740245}
[0m18:36:27.672317 [debug] [MainThread]: Command `dbt init` succeeded at 18:36:27.672249 after 26.90 seconds
[0m18:36:27.672552 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10840a090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108980ef0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108a7bad0>]}
[0m18:36:27.672775 [debug] [MainThread]: Flushing usage events
[0m16:23:49.199417 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106509c70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107b93500>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107b93260>]}


============================== 16:23:49.201911 | c0a9dcf5-16c3-46f5-b76d-1f1af310c6b0 ==============================
[0m16:23:49.201911 [info ] [MainThread]: Running with dbt=1.8.9
[0m16:23:49.202221 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/friedrichtenhagen/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:23:49.207305 [info ] [MainThread]: dbt version: 1.8.9
[0m16:23:49.207508 [info ] [MainThread]: python version: 3.12.7
[0m16:23:49.207725 [info ] [MainThread]: python path: /Users/friedrichtenhagen/coding/marketing_data_engineering_project/marketing_dwh_env/bin/python3.12
[0m16:23:49.207953 [info ] [MainThread]: os info: macOS-14.5-arm64-arm-64bit
[0m16:23:49.271405 [info ] [MainThread]: Using profiles dir at /Users/friedrichtenhagen/.dbt
[0m16:23:49.271676 [info ] [MainThread]: Using profiles.yml file at /Users/friedrichtenhagen/.dbt/profiles.yml
[0m16:23:49.271823 [info ] [MainThread]: Using dbt_project.yml file at /Users/friedrichtenhagen/coding/marketing_data_engineering_project/dbt/dbt_project.yml
[0m16:23:49.272000 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m16:23:49.273385 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.112538956, "process_in_blocks": "0", "process_kernel_time": 0.072226, "process_mem_max_rss": "117555200", "process_out_blocks": "0", "process_user_time": 0.696336}
[0m16:23:49.273718 [debug] [MainThread]: Command `dbt debug` failed at 16:23:49.273660 after 0.11 seconds
[0m16:23:49.273904 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106f60b60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107ce3e30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107c33f20>]}
[0m16:23:49.274075 [debug] [MainThread]: Flushing usage events
[0m16:25:04.314423 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1115314f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111b93590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111b93320>]}


============================== 16:25:04.317368 | c0680ea4-7097-4755-b741-f9dcf231c1dd ==============================
[0m16:25:04.317368 [info ] [MainThread]: Running with dbt=1.8.9
[0m16:25:04.317685 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/friedrichtenhagen/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:25:04.326996 [info ] [MainThread]: dbt version: 1.8.9
[0m16:25:04.327249 [info ] [MainThread]: python version: 3.12.7
[0m16:25:04.327400 [info ] [MainThread]: python path: /Users/friedrichtenhagen/coding/marketing_data_engineering_project/marketing_dwh_env/bin/python3.12
[0m16:25:04.327575 [info ] [MainThread]: os info: macOS-14.5-arm64-arm-64bit
[0m16:25:04.392652 [info ] [MainThread]: Using profiles dir at /Users/friedrichtenhagen/.dbt
[0m16:25:04.392947 [info ] [MainThread]: Using profiles.yml file at /Users/friedrichtenhagen/.dbt/profiles.yml
[0m16:25:04.393152 [info ] [MainThread]: Using dbt_project.yml file at /Users/friedrichtenhagen/coding/marketing_data_engineering_project/dbt/dbt_project.yml
[0m16:25:04.393358 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m16:25:04.394741 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.115934, "process_in_blocks": "0", "process_kernel_time": 0.092106, "process_mem_max_rss": "115933184", "process_out_blocks": "0", "process_user_time": 0.707597}
[0m16:25:04.395046 [debug] [MainThread]: Command `dbt debug` failed at 16:25:04.394996 after 0.12 seconds
[0m16:25:04.395228 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111683080>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111b930e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1113b4e60>]}
[0m16:25:04.395396 [debug] [MainThread]: Flushing usage events
[0m17:41:03.758582 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1040a23f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1055d36b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1055d3410>]}


============================== 17:41:03.761664 | 419cf6d9-48d1-4002-905d-8261fa134702 ==============================
[0m17:41:03.761664 [info ] [MainThread]: Running with dbt=1.8.9
[0m17:41:03.762016 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/friedrichtenhagen/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m17:41:03.762305 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/friedrichtenhagen/coding/marketing_data_engineering_project/dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:41:03.763623 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.042728044, "process_in_blocks": "0", "process_kernel_time": 0.072388, "process_mem_max_rss": "99221504", "process_out_blocks": "0", "process_user_time": 0.645924}
[0m17:41:03.763948 [debug] [MainThread]: Command `dbt run` failed at 17:41:03.763897 after 0.04 seconds
[0m17:41:03.764124 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1050335c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1055d36b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1055d3500>]}
[0m17:41:03.764280 [debug] [MainThread]: Flushing usage events
